ifneq ($(KERNELRELEASE),)
obj-m :=kpp.o
else
CURRENT_PATH := $(shell pwd)
LINUX_KERNEL_PATH := /usr/src/linux-headers-2.6.35-22
all:
	make -C $(LINUX_KERNEL_PATH) M=$(CURRENT_PATH) modules
clean:
	rm -rf .*.cmd *.o *.mod.c *.ko .tmp_versions Module.symvers .Makefile.swp
endif
